# netlify.toml

[build]
  # Netlify에서 실행할 빌드 명령을 비워둡니다.
  # GitHub Actions에서 이미 빌드했으므로 여기서는 아무것도 할 필요가 없습니다.
  command = "echo 'Build already done in GitHub Actions'"
  
  # 배포할 디렉터리를 지정합니다.
  publish = "out"