CREATE TYPE "public"."metric_type" AS ENUM('marketcap', 'bps', 'per', 'pbr', 'eps', 'div', 'dps');--> statement-breakpoint
CREATE TABLE "bppedd" (
	"id" serial PRIMARY KEY NOT NULL,
	"security_id" text,
	"date" timestamp NOT NULL,
	"ticker" text NOT NULL,
	"name" text,
	"kor_name" text,
	"exchange" text NOT NULL,
	"bps" double precision NOT NULL,
	"per" double precision NOT NULL,
	"pbr" double precision NOT NULL,
	"eps" double precision NOT NULL,
	"div" double precision NOT NULL,
	"dps" double precision NOT NULL,
	"year" integer NOT NULL,
	"month" integer NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "company" (
	"company_id" text PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	"kor_name" text NOT NULL,
	"address" text,
	"kor_address" text,
	"country" text,
	"type" text,
	"tel" text,
	"fax" text,
	"postal_code" text,
	"homepage" text,
	"employees" integer,
	"industry" text,
	"established_date" timestamp,
	"marketcap" bigint,
	"marketcap_rank" integer,
	"marketcap_prior_rank" integer,
	"marketcap_date" timestamp,
	"logo" text,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "display_name" (
	"id" serial PRIMARY KEY NOT NULL,
	"value" text NOT NULL,
	"order" integer DEFAULT 0,
	"company_id" text NOT NULL,
	"company_name" text NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "marketcap" (
	"id" serial PRIMARY KEY NOT NULL,
	"security_id" text,
	"date" timestamp NOT NULL,
	"ticker" text NOT NULL,
	"name" text,
	"kor_name" text,
	"exchange" text NOT NULL,
	"marketcap" bigint NOT NULL,
	"volume" bigint NOT NULL,
	"transaction" bigint,
	"shares" bigint NOT NULL,
	"year" integer NOT NULL,
	"month" integer NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "pension" (
	"id" serial PRIMARY KEY NOT NULL,
	"data_created_ym" timestamp NOT NULL,
	"company_id" varchar(20),
	"company_name" varchar(100) NOT NULL,
	"business_reg_num" varchar(10),
	"join_status" varchar(5),
	"zip_code" varchar(10),
	"lot_number_address" varchar(50),
	"road_name_address" varchar(50),
	"legal_dong_addr_code" varchar(15),
	"admin_dong_addr_code" varchar(15),
	"addr_sido_code" varchar(5),
	"addr_sigungu_code" varchar(5),
	"addr_emdong_code" varchar(5),
	"workplace_type" varchar(5),
	"industry_code" varchar(10),
	"industry_name" varchar(50),
	"applied_at" timestamp,
	"re_registered_at" timestamp,
	"withdrawn_at" timestamp,
	"subscriber_count" integer,
	"monthly_notice_amount" bigint,
	"new_subscribers" integer,
	"lost_subscribers" integer,
	"avg_fee" integer,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "price" (
	"id" serial PRIMARY KEY NOT NULL,
	"security_id" text,
	"date" timestamp NOT NULL,
	"ticker" text NOT NULL,
	"name" text,
	"kor_name" text,
	"exchange" text,
	"open" double precision NOT NULL,
	"high" double precision NOT NULL,
	"low" double precision NOT NULL,
	"close" double precision NOT NULL,
	"volume" bigint NOT NULL,
	"fvolume" double precision,
	"transaction" bigint,
	"rate" double precision,
	"year" integer NOT NULL,
	"month" integer NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "search_name" (
	"id" serial PRIMARY KEY NOT NULL,
	"value" text NOT NULL,
	"company_id" text NOT NULL,
	"company_name" text NOT NULL,
	"order" integer DEFAULT 0,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "security" (
	"security_id" text PRIMARY KEY NOT NULL,
	"company_id" text,
	"ticker" text NOT NULL,
	"name" text NOT NULL,
	"kor_name" text NOT NULL,
	"listing_date" timestamp,
	"delisting_date" timestamp,
	"type" text,
	"exchange" text NOT NULL,
	"country" text,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	"price" double precision,
	"price_date" timestamp,
	"shares" bigint,
	"shares_date" timestamp,
	"marketcap" bigint,
	"marketcap_date" timestamp,
	"bps" double precision,
	"bps_date" timestamp,
	"per" double precision,
	"per_date" timestamp,
	"pbr" double precision,
	"pbr_date" timestamp,
	"eps" double precision,
	"eps_date" timestamp,
	"div" double precision,
	"div_date" timestamp,
	"dps" double precision,
	"dps_date" timestamp
);
--> statement-breakpoint
CREATE TABLE "security_rank" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "security_rank_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"security_id" text NOT NULL,
	"metric_type" "metric_type" NOT NULL,
	"rank_date" date NOT NULL,
	"current_rank" integer,
	"prior_rank" integer,
	"value" double precision,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "stockcodename" (
	"date" timestamp NOT NULL,
	"ticker" text NOT NULL,
	"name" text,
	"exchange" text NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "stockcodename_date_ticker_exchange_pk" PRIMARY KEY("date","ticker","exchange")
);
--> statement-breakpoint
CREATE TABLE "tmp_bppedds" (
	"date" timestamp NOT NULL,
	"ticker" text NOT NULL,
	"bps" double precision NOT NULL,
	"per" double precision NOT NULL,
	"pbr" double precision NOT NULL,
	"eps" double precision NOT NULL,
	"div" double precision NOT NULL,
	"dps" double precision NOT NULL,
	"exchange" text NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "tmp_bppedds_date_ticker_exchange_pk" PRIMARY KEY("date","ticker","exchange")
);
--> statement-breakpoint
CREATE TABLE "tmp_marketcaps" (
	"date" timestamp NOT NULL,
	"ticker" text NOT NULL,
	"close" double precision NOT NULL,
	"marketcap" bigint NOT NULL,
	"volume" bigint NOT NULL,
	"transaction" bigint,
	"shares" bigint NOT NULL,
	"exchange" text NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "tmp_marketcaps_date_ticker_exchange_pk" PRIMARY KEY("date","ticker","exchange")
);
--> statement-breakpoint
CREATE TABLE "tmp_prices" (
	"date" timestamp NOT NULL,
	"ticker" text NOT NULL,
	"open" double precision NOT NULL,
	"high" double precision NOT NULL,
	"low" double precision NOT NULL,
	"close" double precision NOT NULL,
	"volume" bigint NOT NULL,
	"transaction" bigint,
	"rate" double precision,
	"exchange" text NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "tmp_prices_date_ticker_exchange_pk" PRIMARY KEY("date","ticker","exchange")
);
--> statement-breakpoint
ALTER TABLE "bppedd" ADD CONSTRAINT "bppedd_security_id_security_security_id_fk" FOREIGN KEY ("security_id") REFERENCES "public"."security"("security_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "display_name" ADD CONSTRAINT "display_name_company_id_company_company_id_fk" FOREIGN KEY ("company_id") REFERENCES "public"."company"("company_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "marketcap" ADD CONSTRAINT "marketcap_security_id_security_security_id_fk" FOREIGN KEY ("security_id") REFERENCES "public"."security"("security_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pension" ADD CONSTRAINT "pension_company_id_company_company_id_fk" FOREIGN KEY ("company_id") REFERENCES "public"."company"("company_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "price" ADD CONSTRAINT "price_security_id_security_security_id_fk" FOREIGN KEY ("security_id") REFERENCES "public"."security"("security_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "search_name" ADD CONSTRAINT "search_name_company_id_company_company_id_fk" FOREIGN KEY ("company_id") REFERENCES "public"."company"("company_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "security" ADD CONSTRAINT "security_company_id_company_company_id_fk" FOREIGN KEY ("company_id") REFERENCES "public"."company"("company_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "security_rank" ADD CONSTRAINT "security_rank_security_id_security_security_id_fk" FOREIGN KEY ("security_id") REFERENCES "public"."security"("security_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "bppedd_security_id_idx" ON "bppedd" USING btree ("security_id");--> statement-breakpoint
CREATE INDEX "bppedd_date_idx" ON "bppedd" USING btree ("date");--> statement-breakpoint
CREATE INDEX "bppedd_ticker_idx" ON "bppedd" USING btree ("ticker");--> statement-breakpoint
CREATE INDEX "bppedd_year_month_idx" ON "bppedd" USING btree ("year","month");--> statement-breakpoint
CREATE INDEX "bppedd_created_at_idx" ON "bppedd" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "bppedd_security_id_date_idx" ON "bppedd" USING btree ("security_id","date");--> statement-breakpoint
CREATE INDEX "bppedd_date_exchange_idx" ON "bppedd" USING btree ("date","exchange");--> statement-breakpoint
CREATE INDEX "company_name_idx" ON "company" USING btree ("name");--> statement-breakpoint
CREATE INDEX "company_kor_name_idx" ON "company" USING btree ("kor_name");--> statement-breakpoint
CREATE INDEX "company_country_idx" ON "company" USING btree ("country");--> statement-breakpoint
CREATE INDEX "company_type_idx" ON "company" USING btree ("type");--> statement-breakpoint
CREATE INDEX "company_created_at_idx" ON "company" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "idx_company_marketcap_listed" ON "company" USING btree ("marketcap" DESC NULLS LAST) WHERE "company"."type" = '상장법인';--> statement-breakpoint
CREATE INDEX "display_name_company_id_idx" ON "display_name" USING btree ("company_id");--> statement-breakpoint
CREATE INDEX "display_name_value_idx" ON "display_name" USING btree ("value");--> statement-breakpoint
CREATE INDEX "display_name_created_at_idx" ON "display_name" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "marketcap_security_id_idx" ON "marketcap" USING btree ("security_id");--> statement-breakpoint
CREATE INDEX "marketcap_date_idx" ON "marketcap" USING btree ("date");--> statement-breakpoint
CREATE INDEX "marketcap_ticker_idx" ON "marketcap" USING btree ("ticker");--> statement-breakpoint
CREATE INDEX "marketcap_year_month_idx" ON "marketcap" USING btree ("year","month");--> statement-breakpoint
CREATE INDEX "marketcap_created_at_idx" ON "marketcap" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "marketcap_security_id_date_idx" ON "marketcap" USING btree ("security_id","date");--> statement-breakpoint
CREATE INDEX "marketcap_date_exchange_idx" ON "marketcap" USING btree ("date","exchange");--> statement-breakpoint
CREATE INDEX "price_security_id_idx" ON "price" USING btree ("security_id");--> statement-breakpoint
CREATE INDEX "price_date_idx" ON "price" USING btree ("date");--> statement-breakpoint
CREATE INDEX "price_ticker_idx" ON "price" USING btree ("ticker");--> statement-breakpoint
CREATE INDEX "price_year_month_idx" ON "price" USING btree ("year","month");--> statement-breakpoint
CREATE INDEX "price_created_at_idx" ON "price" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "price_security_id_date_idx" ON "price" USING btree ("security_id","date");--> statement-breakpoint
CREATE INDEX "price_exchange_date_idx" ON "price" USING btree ("exchange","date");--> statement-breakpoint
CREATE INDEX "price_ticker_exchange_idx" ON "price" USING btree ("ticker","exchange");--> statement-breakpoint
CREATE INDEX "price_date_exchange_idx" ON "price" USING btree ("date","exchange");--> statement-breakpoint
CREATE INDEX "search_name_company_id_idx" ON "search_name" USING btree ("company_id");--> statement-breakpoint
CREATE INDEX "search_name_value_idx" ON "search_name" USING btree ("value");--> statement-breakpoint
CREATE INDEX "search_name_created_at_idx" ON "search_name" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "security_company_id_idx" ON "security" USING btree ("company_id");--> statement-breakpoint
CREATE INDEX "security_ticker_idx" ON "security" USING btree ("ticker");--> statement-breakpoint
CREATE INDEX "security_name_idx" ON "security" USING btree ("name");--> statement-breakpoint
CREATE INDEX "security_kor_name_idx" ON "security" USING btree ("kor_name");--> statement-breakpoint
CREATE INDEX "security_exchange_idx" ON "security" USING btree ("exchange");--> statement-breakpoint
CREATE INDEX "security_created_at_idx" ON "security" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "security_exchange_security_id_idx" ON "security" USING btree ("exchange","security_id") WHERE "security"."delisting_date" IS NULL;--> statement-breakpoint
CREATE INDEX "security_exchange_ticker_idx" ON "security" USING btree ("exchange","ticker");--> statement-breakpoint
CREATE INDEX "idx_security_marketcap_active" ON "security" USING btree ("marketcap" DESC NULLS LAST) WHERE "security"."delisting_date" IS NULL;--> statement-breakpoint
CREATE UNIQUE INDEX "uq_security_rank_unique_entry" ON "security_rank" USING btree ("security_id","metric_type","rank_date");--> statement-breakpoint
CREATE INDEX "idx_security_rank_metric_date_rank" ON "security_rank" USING btree ("metric_type","rank_date","current_rank");--> statement-breakpoint
CREATE INDEX "idx_security_rank_security_metric_date" ON "security_rank" USING btree ("security_id","metric_type","rank_date");--> statement-breakpoint
CREATE INDEX "idx_security_rank_metric_date_value" ON "security_rank" USING btree ("metric_type","rank_date","value");--> statement-breakpoint
CREATE INDEX "stockcodename_ticker_idx" ON "stockcodename" USING btree ("ticker");--> statement-breakpoint
CREATE INDEX "stockcodename_name_idx" ON "stockcodename" USING btree ("name");--> statement-breakpoint
CREATE INDEX "stockcodename_exchange_idx" ON "stockcodename" USING btree ("exchange");--> statement-breakpoint
CREATE INDEX "stockcodename_date_exchange_idx" ON "stockcodename" USING btree ("date","exchange");--> statement-breakpoint
CREATE INDEX "stockcodename_exchange_ticker_idx" ON "stockcodename" USING btree ("exchange","ticker");--> statement-breakpoint
CREATE INDEX "tmp_bppedds_ticker_idx" ON "tmp_bppedds" USING btree ("ticker");--> statement-breakpoint
CREATE INDEX "tmp_bppedds_date_idx" ON "tmp_bppedds" USING btree ("date");--> statement-breakpoint
CREATE INDEX "tmp_bppedds_exchange_idx" ON "tmp_bppedds" USING btree ("exchange");--> statement-breakpoint
CREATE INDEX "tmp_bppedds_date_exchange_idx" ON "tmp_bppedds" USING btree ("date","exchange");--> statement-breakpoint
CREATE INDEX "tmp_marketcaps_ticker_idx" ON "tmp_marketcaps" USING btree ("ticker");--> statement-breakpoint
CREATE INDEX "tmp_marketcaps_date_idx" ON "tmp_marketcaps" USING btree ("date");--> statement-breakpoint
CREATE INDEX "tmp_marketcaps_exchange_idx" ON "tmp_marketcaps" USING btree ("exchange");--> statement-breakpoint
CREATE INDEX "tmp_marketcaps_date_exchange_idx" ON "tmp_marketcaps" USING btree ("date","exchange");--> statement-breakpoint
CREATE INDEX "tmp_prices_ticker_idx" ON "tmp_prices" USING btree ("ticker");--> statement-breakpoint
CREATE INDEX "tmp_prices_date_idx" ON "tmp_prices" USING btree ("date");--> statement-breakpoint
CREATE INDEX "tmp_prices_exchange_idx" ON "tmp_prices" USING btree ("exchange");--> statement-breakpoint
CREATE INDEX "tmp_prices_date_exchange_idx" ON "tmp_prices" USING btree ("date","exchange");