name: Build and Deploy to R2

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_and_deploy:
    runs-on: self-hosted
    timeout-minutes: 120
    env:
      NEXT_TELEMETRY_DISABLED: "1"
      # GitHub Actions ubuntu-latest: 2 CPU cores, 8GB RAM
      NODE_OPTIONS: "--max-old-space-size=6144"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "pnpm"
          cache-dependency-path: pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Free up disk space
        run: |
          echo "=== Initial disk usage ==="
          df -h
          echo "=== Cleaning up space ==="

          # Remove unnecessary packages
          sudo apt-get remove -y '^dotnet-.*' '^llvm-.*' 'php.*' '^mongodb-.*' '^mysql-.*' 2>/dev/null || true
          sudo apt-get autoremove -y 2>/dev/null || true
          sudo apt-get clean

          # Remove unused tool caches
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf /usr/local/share/boost
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/hostedtoolcache/CodeQL
          sudo rm -rf /opt/hostedtoolcache/PyPy
          sudo rm -rf /opt/hostedtoolcache/go
          sudo rm -rf /opt/hostedtoolcache/Ruby

          # Clean package manager caches
          sudo rm -rf /tmp/*
          sudo rm -rf ~/.npm

          # Clean Docker
          docker system prune -af --volumes 2>/dev/null || true

          echo "=== Final disk usage ==="
          df -h

      - name: Build Next.js with parallel processing
        env:
          POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
          POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
        run: |
          echo "=== Starting optimized build with parallel processing ==="
          chmod +x scripts/build-parallel-real.sh
          pnpm run build

      - name: Upload to R2
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: apac
          R2_BUCKET_NAME: ${{ secrets.R2_BUCKET_NAME }}
          R2_ACCOUNT_ID: ${{ secrets.R2_ACCOUNT_ID }}
          R2_ENDPOINT_URL: https://${{ secrets.R2_ACCOUNT_ID }}.r2.cloudflarestorage.com
        run: |
          aws s3 sync ./out s3://${{ env.R2_BUCKET_NAME }}/ \
            --endpoint-url ${{ env.R2_ENDPOINT_URL }} \
            --delete
